#!/bin/bash -x
#
#


# -- write phylogenetic tree
#
echo "((((A,B),C),(D,E)),F);" >| exW.tree

cat << ENDE >| exW.cm
0 { gmm{0} gmr{0} gro{0}}

1 { gmm{1} gmr{1} gro{1}}

2 { gmm{1} gmr{2} gro{2}}
ENDE

# -- create a simple nuc model with randomized parameters, and
#    equilibrate model.
#
../bin/CodeAxe -create-model -site-model nuc -rate-model nonrev -root-model full -tree-file exW.tree -cat-model-file exW.cm -unlock-cat-prob -random-param |\
../bin/CodeAxe -norm -in-model - >| exW.model.random

# -- simulate sequences from the equilibrated random model
#
../bin/CodeAxe -sim -sim-size 100000 -sim-model discrete -in-model exW.model.random >| exW.data.sim

# self lhood
#
../bin/CodeAxe -lhood -in-model exW.model.random -in-data exW.data.sim >| exW.model.random.lhood



# -- create a starting model
#
../bin/CodeAxe -create-model -site-model nuc -rate-model nonrev -root-model full -tree-file exW.tree -cat-model-file exW.cm -unlock-cat-prob -in-data exW.data.sim >| exW.model.start

# -- train model
#
../bin/CodeAxe -ml -in-model exW.model.start -in-data exW.data.sim >| exW.model.trained 2>| exW.model.ml.stderr

# -- get the likelihood & likelihood/codon of the trained model
#
../bin/CodeAxe -lhood -in-model exW.model.trained -in-data exW.data.sim >| exW.model.trained.lhood

# -- summarize parameters from the trained model
#
../bin/CodeAxe -report-model -in-model exW.model.trained >| exW.model.trained.report

